"""Static tag data for the table tennis coach MVP."""

from __future__ import annotations

from typing import Any


scoring_reasons: list[dict[str, Any]] = [
    {
        "id": "S001",
        "name_cn": "发短下旋后对手冒高",
        "name_en": "Short backspin serve forced a high return",
        "category": "serve",
        "phase": "serve_receive",
        "tech": "serve",
        "spin": "backspin",
        "placement": "short",
        "result_type": "opponent_pop_up",
        "description": "发短下旋后，对手回球偏高，我方直接获得进攻机会并得分。",
    },
    {
        "id": "S002",
        "name_cn": "发不转后对手判断失误",
        "name_en": "No-spin serve caused a read error",
        "category": "serve",
        "phase": "serve_receive",
        "tech": "serve",
        "spin": "no_spin",
        "placement": "mixed",
        "result_type": "opponent_misread",
        "description": "通过不转或近似不转发球，让对手吃旋转判断错误而失分。",
    },
    {
        "id": "S003",
        "name_cn": "发急长球直接得分",
        "name_en": "Fast long serve won the point directly",
        "category": "serve",
        "phase": "serve_receive",
        "tech": "serve",
        "spin": "mixed",
        "placement": "long",
        "result_type": "direct_point",
        "description": "发球速度快、落点深，对手来不及处理或直接失误。",
    },
    {
        "id": "S004",
        "name_cn": "发球后对手接发冒高",
        "name_en": "Serve produced a high receive for attack",
        "category": "serve",
        "phase": "serve_receive",
        "tech": "serve",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "attack_chance",
        "description": "发球质量较高，对手接发偏高，我方借机上手得分。",
    },
    {
        "id": "S005",
        "name_cn": "发球变化让对手不适应",
        "name_en": "Serve variation disrupted the opponent",
        "category": "serve",
        "phase": "serve_receive",
        "tech": "serve",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "variation_success",
        "description": "通过旋转、节奏或长短变化打乱对手接发节奏并得分。",
    },
    {
        "id": "S006",
        "name_cn": "接发球直接上手得分",
        "name_en": "Direct receive attack won the point",
        "category": "receive",
        "phase": "serve_receive",
        "tech": "receive_attack",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "direct_attack_point",
        "description": "接发时直接挑、拧、冲或拍击，上手后直接得分。",
    },
    {
        "id": "S007",
        "name_cn": "接急长球直接进攻得分",
        "name_en": "Attacked a long serve successfully",
        "category": "receive",
        "phase": "serve_receive",
        "tech": "receive_attack",
        "spin": "mixed",
        "placement": "long",
        "result_type": "long_serve_attack",
        "description": "对手发球出台或偏长，我方直接抢攻得分。",
    },
    {
        "id": "S008",
        "name_cn": "接发控制后对手回球质量差",
        "name_en": "Controlled receive caused a weak next ball",
        "category": "receive",
        "phase": "serve_receive",
        "tech": "receive_control",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "weak_reply_created",
        "description": "接发先控制住质量，对手下一板回球偏软或偏高，我方再得分。",
    },
    {
        "id": "S009",
        "name_cn": "第三板抢攻得分",
        "name_en": "Third-ball attack won the point",
        "category": "third_ball",
        "phase": "early_attack",
        "tech": "third_ball_attack",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "third_ball_point",
        "description": "通过发球后衔接第三板主动抢攻，直接得分。",
    },
    {
        "id": "S010",
        "name_cn": "发球后连续进攻压制得分",
        "name_en": "Serve plus follow-up attack pressure scored",
        "category": "third_ball",
        "phase": "early_attack",
        "tech": "serve_plus_attack",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "pressure_attack_point",
        "description": "发球后连续两三板保持主动，压住对手后得分。",
    },
    {
        "id": "S011",
        "name_cn": "对手回球质量差被我抢攻得分",
        "name_en": "Weak return was punished immediately",
        "category": "third_ball",
        "phase": "early_attack",
        "tech": "first_attack",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "punish_weak_ball",
        "description": "对手回球偏高、偏浅或偏慢，我方抓住机会抢攻得分。",
    },
    {
        "id": "S012",
        "name_cn": "前三板节奏压制得分",
        "name_en": "Early-phase rhythm pressure won the point",
        "category": "third_ball",
        "phase": "early_attack",
        "tech": "tempo_control",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "tempo_pressure",
        "description": "在发球、接发和前三板阶段抢到节奏优势并得分。",
    },
    {
        "id": "S013",
        "name_cn": "正手进攻压制得分",
        "name_en": "Forehand attack pressure scored",
        "category": "rally",
        "phase": "rally",
        "tech": "forehand_attack",
        "spin": "topspin",
        "placement": "mixed",
        "result_type": "forehand_pressure",
        "description": "依靠正手连续进攻或高质量一板形成压制并得分。",
    },
    {
        "id": "S014",
        "name_cn": "反手相持压制得分",
        "name_en": "Backhand rally pressure scored",
        "category": "rally",
        "phase": "rally",
        "tech": "backhand_rally",
        "spin": "topspin",
        "placement": "mixed",
        "result_type": "backhand_pressure",
        "description": "在反手相持中占优，持续压住对手并最终得分。",
    },
    {
        "id": "S015",
        "name_cn": "连续进攻多板压制得分",
        "name_en": "Multi-ball attack pressure won the point",
        "category": "rally",
        "phase": "rally",
        "tech": "multi_ball_attack",
        "spin": "topspin",
        "placement": "mixed",
        "result_type": "multi_ball_pressure",
        "description": "通过多板持续进攻，让对手顶不住，最后得分。",
    },
    {
        "id": "S016",
        "name_cn": "变线打穿对手得分",
        "name_en": "Change of direction broke through the opponent",
        "category": "rally",
        "phase": "rally",
        "tech": "placement_change",
        "spin": "mixed",
        "placement": "wide",
        "result_type": "direction_change_point",
        "description": "通过斜直线变化或线路突然切换，直接打穿对手。",
    },
    {
        "id": "S017",
        "name_cn": "中路或追身压制得分",
        "name_en": "Body or middle-line pressure scored",
        "category": "rally",
        "phase": "rally",
        "tech": "body_attack",
        "spin": "mixed",
        "placement": "middle",
        "result_type": "body_pressure_point",
        "description": "针对中路、追身或衔接不舒服的位置进攻并得分。",
    },
    {
        "id": "S018",
        "name_cn": "对手处理短球能力差而得分",
        "name_en": "Opponent struggled with short balls",
        "category": "opponent_weakness",
        "phase": "pattern",
        "tech": "short_game",
        "spin": "mixed",
        "placement": "short",
        "result_type": "exploit_short_game_weakness",
        "description": "发现对手短球处理差，通过短球控制或短球变化得分。",
    },
    {
        "id": "S019",
        "name_cn": "针对对手薄弱侧得分",
        "name_en": "Targeted the opponent's weaker side successfully",
        "category": "opponent_weakness",
        "phase": "pattern",
        "tech": "target_weak_side",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "exploit_side_weakness",
        "description": "持续攻击对手较弱的一侧，如反手位或正手位，从而得分。",
    },
    {
        "id": "S020",
        "name_cn": "对手不适应旋转变化而得分",
        "name_en": "Opponent failed to adapt to spin variation",
        "category": "opponent_weakness",
        "phase": "pattern",
        "tech": "spin_variation",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "exploit_spin_weakness",
        "description": "通过上下旋、不转、侧旋等变化，让对手处理失误。",
    },
]


losing_reasons: list[dict[str, Any]] = [
    {
        "id": "L001",
        "name_cn": "吃对手发球",
        "name_en": "Misread the opponent's serve",
        "category": "receive",
        "phase": "serve_receive",
        "tech": "receive",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "serve_receive_error",
        "description": "对对手发球的旋转、落点或节奏判断错误，直接失分。",
    },
    {
        "id": "L002",
        "name_cn": "接急长球反应慢",
        "name_en": "Late reaction to a fast long serve",
        "category": "receive",
        "phase": "serve_receive",
        "tech": "receive",
        "spin": "mixed",
        "placement": "long",
        "result_type": "late_on_long_serve",
        "description": "对手发急长球时来不及处理，导致回球失误或质量过差。",
    },
    {
        "id": "L003",
        "name_cn": "摆短过高",
        "name_en": "Short receive was too high",
        "category": "receive",
        "phase": "serve_receive",
        "tech": "short_receive",
        "spin": "mixed",
        "placement": "short",
        "result_type": "high_short_ball",
        "description": "摆短质量不够，回球偏高，被对手直接上手。",
    },
    {
        "id": "L004",
        "name_cn": "摆短出台",
        "name_en": "Short receive went too long",
        "category": "receive",
        "phase": "serve_receive",
        "tech": "short_receive",
        "spin": "mixed",
        "placement": "half_long",
        "result_type": "short_ball_too_long",
        "description": "原本想摆短，但球出台或半出台，给了对手进攻机会。",
    },
    {
        "id": "L005",
        "name_cn": "搓长质量差被抢攻",
        "name_en": "Long push was attacked",
        "category": "receive",
        "phase": "serve_receive",
        "tech": "push",
        "spin": "backspin",
        "placement": "long",
        "result_type": "weak_long_push",
        "description": "搓长回球质量不足，旋转弱、落点差或偏高，被对手直接抢攻。",
    },
    {
        "id": "L006",
        "name_cn": "接发冒高被打",
        "name_en": "Receive popped up and got punished",
        "category": "receive",
        "phase": "serve_receive",
        "tech": "receive",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "high_receive_punished",
        "description": "接发球回得过高，给了对手明显的进攻机会。",
    },
    {
        "id": "L007",
        "name_cn": "发球被对手直接上手",
        "name_en": "Serve was attacked immediately",
        "category": "serve",
        "phase": "serve_receive",
        "tech": "serve",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "serve_attacked",
        "description": "发球质量不够或落点过于固定，被对手直接挑、拧、冲。",
    },
    {
        "id": "L008",
        "name_cn": "发球变化太少被适应",
        "name_en": "Serve pattern became predictable",
        "category": "serve",
        "phase": "serve_receive",
        "tech": "serve",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "predictable_serve",
        "description": "发球套路重复过多，对手逐渐适应并开始占优。",
    },
    {
        "id": "L009",
        "name_cn": "第三板抢攻失误",
        "name_en": "Missed the third-ball attack",
        "category": "third_ball",
        "phase": "early_attack",
        "tech": "third_ball_attack",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "third_ball_attack_error",
        "description": "本来有主动上手机会，但第三板处理失误直接丢分。",
    },
    {
        "id": "L010",
        "name_cn": "起下旋失误",
        "name_en": "Missed opening against backspin",
        "category": "attack",
        "phase": "early_attack",
        "tech": "loop_opening",
        "spin": "backspin",
        "placement": "long",
        "result_type": "failed_opening_loop",
        "description": "对下旋球起板失误，未能建立主动。",
    },
    {
        "id": "L011",
        "name_cn": "上手后衔接不好被反压",
        "name_en": "Poor follow-up after attacking first",
        "category": "attack",
        "phase": "early_attack",
        "tech": "attack_followup",
        "spin": "topspin",
        "placement": "mixed",
        "result_type": "weak_followup_after_attack",
        "description": "虽然先上手了，但下一板衔接不到位，被对手反压制。",
    },
    {
        "id": "L012",
        "name_cn": "正手进攻失误多",
        "name_en": "Too many forehand attack errors",
        "category": "rally",
        "phase": "rally",
        "tech": "forehand_attack",
        "spin": "topspin",
        "placement": "mixed",
        "result_type": "forehand_attack_errors",
        "description": "正手进攻稳定性不够，主动失误较多。",
    },
    {
        "id": "L013",
        "name_cn": "反手相持顶不住",
        "name_en": "Could not hold in backhand rallies",
        "category": "rally",
        "phase": "rally",
        "tech": "backhand_rally",
        "spin": "topspin",
        "placement": "mixed",
        "result_type": "backhand_rally_lost",
        "description": "在反手相持中处于下风，逐渐被压住并失分。",
    },
    {
        "id": "L014",
        "name_cn": "连续相持中主动失误",
        "name_en": "Unforced error during rally",
        "category": "rally",
        "phase": "rally",
        "tech": "rally_control",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "unforced_rally_error",
        "description": "相持中没有受到特别强压，但自己先出现主动失误。",
    },
    {
        "id": "L015",
        "name_cn": "被对手变线打穿",
        "name_en": "Got beaten by change of direction",
        "category": "rally",
        "phase": "rally",
        "tech": "placement_response",
        "spin": "mixed",
        "placement": "wide",
        "result_type": "lost_to_direction_change",
        "description": "对手通过斜直线变化或突然变线，直接打穿我方站位。",
    },
    {
        "id": "L016",
        "name_cn": "被追身或中路压制",
        "name_en": "Got jammed in the body or middle",
        "category": "rally",
        "phase": "rally",
        "tech": "body_response",
        "spin": "mixed",
        "placement": "middle",
        "result_type": "lost_to_body_attack",
        "description": "对手针对中路或追身进攻，我方处理不舒服而失分。",
    },
    {
        "id": "L017",
        "name_cn": "不适应对手节奏变化",
        "name_en": "Could not adapt to rhythm changes",
        "category": "opponent_pattern",
        "phase": "pattern",
        "tech": "rhythm_adaptation",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "rhythm_change_problem",
        "description": "对手快慢结合、轻重变化或停顿变化较多，我方不适应。",
    },
    {
        "id": "L018",
        "name_cn": "不适应对手旋转变化",
        "name_en": "Could not adapt to spin variation",
        "category": "opponent_pattern",
        "phase": "pattern",
        "tech": "spin_reading",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "spin_variation_problem",
        "description": "对手上下旋、不转或侧旋变化较多，我方判断困难。",
    },
    {
        "id": "L019",
        "name_cn": "对手针对我方弱点连续得分",
        "name_en": "Opponent repeatedly exploited my weakness",
        "category": "opponent_pattern",
        "phase": "pattern",
        "tech": "weakness_exposed",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "weakness_targeted",
        "description": "对手持续攻击我方某一明显短板，如反手位、短球或追身。",
    },
    {
        "id": "L020",
        "name_cn": "关键分处理失误",
        "name_en": "Poor decision or execution on key points",
        "category": "mental_tactical",
        "phase": "key_points",
        "tech": "key_point_execution",
        "spin": "mixed",
        "placement": "mixed",
        "result_type": "key_point_error",
        "description": "在局末或关键分时，战术选择或执行质量下降，导致失分。",
    },
]


opponent_traits: list[dict[str, Any]] = [
    {
        "id": "O001",
        "name_cn": "正手强于反手",
        "name_en": "Forehand stronger than backhand",
        "category": "strength_balance",
        "phase": "global",
        "description": "对手正手能力明显强于反手，反手相对较弱。",
    },
    {
        "id": "O002",
        "name_cn": "反手强于正手",
        "name_en": "Backhand stronger than forehand",
        "category": "strength_balance",
        "phase": "global",
        "description": "对手反手能力强于正手，正手侧存在弱点。",
    },
    {
        "id": "O003",
        "name_cn": "喜欢侧身正手进攻",
        "name_en": "Prefers pivot forehand attack",
        "category": "style",
        "phase": "rally",
        "description": "对手经常侧身用正手进攻，反手位空档较大。",
    },
    {
        "id": "O004",
        "name_cn": "喜欢反手拧/挑",
        "name_en": "Uses backhand flick/banana frequently",
        "category": "receive_style",
        "phase": "serve_receive",
        "description": "对手在接发球时喜欢用反手拧拉或挑打。",
    },
    {
        "id": "O005",
        "name_cn": "接发能力弱",
        "name_en": "Weak at serve receive",
        "category": "weakness",
        "phase": "serve_receive",
        "description": "对手接发球质量不高，容易吃旋转或回球偏高。",
    },
    {
        "id": "O006",
        "name_cn": "发球变化多",
        "name_en": "Varied and tricky serves",
        "category": "serve",
        "phase": "serve_receive",
        "description": "对手发球旋转、落点、节奏变化较多，难以判断。",
    },
    {
        "id": "O007",
        "name_cn": "发球套路单一",
        "name_en": "Predictable serve patterns",
        "category": "serve",
        "phase": "serve_receive",
        "description": "对手发球变化少，可以逐渐适应。",
    },
    {
        "id": "O008",
        "name_cn": "近台快攻型",
        "name_en": "Close-to-table fast attacker",
        "category": "style",
        "phase": "rally",
        "description": "对手喜欢近台快节奏进攻，不愿退台。",
    },
    {
        "id": "O009",
        "name_cn": "相持能力强",
        "name_en": "Strong in rallies",
        "category": "strength",
        "phase": "rally",
        "description": "对手在多板相持中稳定性高，抗压能力强。",
    },
    {
        "id": "O010",
        "name_cn": "相持能力弱",
        "name_en": "Weak in rallies",
        "category": "weakness",
        "phase": "rally",
        "description": "对手在连续相持中容易失误或质量下降。",
    },
    {
        "id": "O011",
        "name_cn": "退台能力强",
        "name_en": "Strong away from table",
        "category": "style",
        "phase": "rally",
        "description": "对手退台后仍能保持稳定对抗。",
    },
    {
        "id": "O012",
        "name_cn": "退台后质量下降",
        "name_en": "Weak when away from table",
        "category": "weakness",
        "phase": "rally",
        "description": "对手一旦被拉出台，回球质量明显下降。",
    },
    {
        "id": "O013",
        "name_cn": "怕追身",
        "name_en": "Struggles with body shots",
        "category": "weakness",
        "phase": "rally",
        "description": "对手在处理中路或追身球时动作不舒服。",
    },
    {
        "id": "O014",
        "name_cn": "怕短球",
        "name_en": "Weak at short game",
        "category": "weakness",
        "phase": "serve_receive",
        "description": "对手短球处理差，容易摆高或出台。",
    },
    {
        "id": "O015",
        "name_cn": "怕连续上旋压制",
        "name_en": "Struggles against continuous topspin",
        "category": "weakness",
        "phase": "rally",
        "description": "对手不适应连续上旋进攻，容易被压住。",
    },
    {
        "id": "O016",
        "name_cn": "不适应旋转变化",
        "name_en": "Struggles with spin variation",
        "category": "weakness",
        "phase": "global",
        "description": "对手对上下旋、不转或侧旋变化判断困难。",
    },
    {
        "id": "O017",
        "name_cn": "节奏变化能力强",
        "name_en": "Good at changing rhythm",
        "category": "strength",
        "phase": "rally",
        "description": "对手擅长快慢结合、停顿变化，打乱节奏。",
    },
    {
        "id": "O018",
        "name_cn": "节奏单一",
        "name_en": "Plays with consistent rhythm",
        "category": "weakness",
        "phase": "rally",
        "description": "对手节奏比较固定，容易被适应或打乱。",
    },
    {
        "id": "O019",
        "name_cn": "长胶打法",
        "name_en": "Long pips player",
        "category": "equipment_style",
        "phase": "global",
        "description": "对手使用长胶，回球旋转特殊，节奏变化明显。",
    },
    {
        "id": "O020",
        "name_cn": "削球防守型",
        "name_en": "Chopper / defensive player",
        "category": "style",
        "phase": "rally",
        "description": "对手以削球、防守为主，比赛节奏较慢。",
    },
]


def build_tag_maps() -> dict[str, dict[str, Any]]:
    all_tags = scoring_reasons + losing_reasons + opponent_traits
    return {tag["id"]: tag for tag in all_tags}
